# Generated by Django 4.1.3 on 2022-11-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0005_alter_connection_following_alter_post_image_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='名無し', max_length=255, verbose_name='名前を入力'),
        ),
    ]
