# Generated by Django 4.1.3 on 2022-11-15 16:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0006_alter_comment_options_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
